MSA/MSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('vehicule/', include('vehicule.urls')),
    path('reservation/', include('reservation.urls')),
    path('partenaire/', include('partenaire.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

MSA/partenaire/urls.py
from django.urls import path
from django.conf.urls import include


from . import views

app_name = 'partenaire'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('Edit/<str:pk>/', views.EditPartenaire, name='EditPartenaire'),
]

MSA/reservation/urls.py
from django.urls import path
from django.conf.urls import include


from . import views

app_name = 'reservation'
urlpatterns = [
    path('', views.index, name='index'),
    path('categorie/', views.choixCategorie, name='choixCategorie'),
    path('choixClient/<str:immatriculation>', views.choixClient, name='choixClient'),
    path('choixVehicule/<str:categorie>', views.choixVehicule, name='choixVehicule'),
    path('liste/', views.ListeReservation, name='ListeReservation'),
    path('add_custumer/<str:custumer>', views.add_custumer, name='add_custumer'),
    path('add_driver/<str:driver>', views.add_driver, name='add_driver'),
    path('save/', views.saveResa, name='save'),
    path('editResa/<str:pk>', views.editResa, name='editResa'),
    path('editContrat/<str:pk>', views.editContrat, name='editContrat'),
]

MSA/vehicule/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

app_name = 'vehicule'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:pk>/', views.detail, name='detail'),
    path('Add/', views.NewVehicule, name='NewVehicule'),
    path('Edit/<str:pk>/', views.EditVehicule, name='EditVehicule'),
    path('categories/', views.listeCategories, name='listeCategories'),
    path('editCategorie/<str:pk>/', views.editCategorie, name='editCategorie'),
    path('newCategorie/', views.newCategorie, name='newCategorie'),
    
]

MSA/reservation/models.py
from django.db import models
from django.db.models import Q
from django.core.exceptions import ValidationError 

from vehicule.models import Vehicule
from partenaire.models import Partenaire


# Create your models here.
class Reservation(models.Model):
    vehicule = models.ForeignKey(
                Vehicule,
                on_delete=models.CASCADE,
                related_name="Vehicule")
    client = models.ForeignKey(
                Partenaire,
                on_delete=models.CASCADE,
                related_name="Client")
    conducteur1 = models.ForeignKey(
                Partenaire,
                on_delete=models.CASCADE,
                related_name="conducteur1")
    conducteur2 = models.ForeignKey(
                Partenaire,
                on_delete=models.CASCADE,
                related_name="conducteur2",null=True, blank=True)
    debut = models.DateTimeField( )
    Fin = models.DateTimeField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    create_by = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        retour = self.vehicule.pk + " du " + self.debut.strftime("%d-%m-%Y") + " au " + self.Fin.strftime("%d-%m-%Y")
        return "%s" % (retour) 

    def save(self, *args, **kwargs):
        if self.debut > self.Fin :  raise ValidationError('Date de début > date fin')

        if self.pk is None:
            if Reservation.objects.filter(
                      Q(vehicule=self.vehicule),
                      ~ (Q(debut__gt=self.debut) & Q(debut__gt=self.Fin)|
                      Q(Fin__lt=self.debut) & Q(Fin__lt=self.Fin))):
                raise ValidationError('Véhicule non dispo.')
        else :
            test = Reservation.objects.filter(
                      ~Q(pk=self.pk),
                      Q(vehicule=self.vehicule),
                      ~ (Q(debut__gt=self.debut) & Q(debut__gt=self.Fin)|
                      Q(Fin__lt=self.debut) & Q(Fin__lt=self.Fin)))

            if test:    raise ValidationError('Véhicule non dispo.')        
        super().save(*args, **kwargs)    

MSA/reservation/forms.py
from django import forms
#from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.admin.widgets import AdminDateWidget, AdminTimeWidget

from .models import Reservation

class dateForm(forms.Form):
    date_debut = forms.DateField( 
        label = 'Date de début', 
        widget=AdminDateWidget(),)
    heure_debut = forms.TimeField(
        label = '',
        widget=AdminTimeWidget(),)
    date_fin = forms.DateField( 
        label = 'Date de fin', 
        widget=AdminDateWidget(),)
    heure_fin = forms.TimeField(
        label = '',
        widget=AdminTimeWidget(),)

class FormRechPartenaire(forms.Form):
    nom = forms.CharField(label='Nom', max_length=100,empty_value=True)
    
class FormReservation(forms.ModelForm):
     class Meta:
        model = Reservation
        fields =  '__all__'

MSA/reservation/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect, HttpResponseRedirect
from django.core import serializers
from datetime import date, datetime, timedelta
from reservation.utils.calcules import CalendrierResa
import calendar
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from vehicule.models import Vehicule
from vehicule.models import Categorie
from partenaire.models import Partenaire
from .models import Reservation
from .forms import dateForm, FormRechPartenaire, FormReservation
 	

class resa_calend:

    def __init__(self, date, vehicule):
        """Constructeur de notre classe"""
        self.date = date
        self.vehicule = vehicule



@login_required(login_url='/accounts/login/')
def index(request):


    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        resa = FormReservation()
        # create a form instance and populate it with data from the request:
        form = dateForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            DateDebut = str(form.cleaned_data['date_debut'])
            HeureDebut = str(form.cleaned_data['heure_debut'])
            DateFin = str(form.cleaned_data['date_fin'])
            HeureFin = str(form.cleaned_data['heure_fin'])

            #Calcule du nombre de jours
            date_delta = form.cleaned_data['date_fin'] - form.cleaned_data['date_debut']

            str_debut = DateDebut  + " " + HeureDebut
            str_Fin = DateFin + " " + HeureFin

            #resa.fields["debut"].initial = datetime.strptime(str_debut, "%Y-%m-%d %H:%M:%S")
            #resa.fields["Fin"].initial = datetime.strptime(str_Fin, "%Y-%m-%d %H:%M:%S")
            
            request.session["date_resa"] = form.data 
            request.session["debut"] = str_debut 
            request.session["fin"] = str_Fin
            request.session["nbjours"] = date_delta.days + 1

            return HttpResponseRedirect('categorie/')

        # if a GET (or any other method) we'll create a blank form
    else:
       form = dateForm()

    titre = 'Réservation'
    context = {
        'form': form,
        'Titre': titre ,
    }
    return render(request, 'reservation/index.html', context )


@login_required(login_url='/accounts/login/')
def ListeReservation(request):
    liste_vehicule = Vehicule.objects.order_by('Immatriculation')
    liste_resa = Reservation.objects.order_by('vehicule')

    calendrierResa = CalendrierResa(datetime.now(),60)

    if 'listResa' in locals(): listResa.clear()
    listResa = [[]]

    cpt = 0
    for vehicule in liste_vehicule :
      cpt = cpt + 1 
      listResa.append([])
      oldCollsAttribut = {'resa':vehicule.pk,'color':'white','link':' ','first':'X','span':'1'}
      listResa[cpt].append(oldCollsAttribut)
      cptSpan = 0
      for mydate in calendrierResa.allDays :

          for resa in liste_resa :
            if resa.vehicule != vehicule: continue

            if resa.debut.strftime("%Y%m%d") <= datetime.strptime(mydate,"%Y%m%d").strftime("%Y%m%d") <= resa.Fin.strftime("%Y%m%d"):
                CollsAttribut = {'resa':resa,'color':'gray','link':'X', 'first':' ','span':''}
                break
            else:
                CollsAttribut = {'resa':'','color':'white','link':' ','first':' ','span':''}

          if oldCollsAttribut['first'] == 'X' :
              oldCollsAttribut = dict(CollsAttribut)
          if oldCollsAttribut != CollsAttribut:
               oldCollsAttribut.update({'span':cptSpan})
               listResa[cpt].append(oldCollsAttribut)  
               cptSpan = 0
               oldCollsAttribut = dict(CollsAttribut)

          cptSpan = cptSpan + 1

      oldCollsAttribut.update({'span':cptSpan})
      listResa[cpt].append(oldCollsAttribut)            

    titre = 'Réservations'
    context = {
        'Titre': titre ,
        'nbDaysInMonth' : calendrierResa.nbDaysMonth,
        'allDates' : calendrierResa.allDays2,
		'listResa' : listResa, 
    } 
    return render(request,'reservation/listeResa.html', context)


@login_required(login_url='/accounts/login/')
def choixCategorie(request):

    liste_categories = Categorie.objects.order_by('categorie')
    titre = 'Choix de la categorie de véhicule'

    prix_loc = {}
    for categorie in liste_categories :
        prix_loc[categorie.pk]  = categorie.tarif * request.session.get('nbjours')


    context = {
        'Titre': titre ,
        'date_resa': request.session.get('date_resa'),
        'nbjours': request.session.get('nbjours'),
        'liste_categories': liste_categories ,
        'prix_loc': prix_loc
    }
    return render(request,'reservation/categorie.html', context)


@login_required(login_url='/accounts/login/')
def choixVehicule(request,categorie):
    titre = 'Choix du véhicule'

    categ = Categorie.objects.filter(pk=categorie)
    total_tarif =  categ[0].tarif * request.session.get('nbjours')
    txt_categorie = "Catégorie : {} - {}/€jours - total {} €".format( categ[0].categorie, categ[0].tarif, total_tarif) 


    debut = datetime.strptime(request.session.get('debut'), "%Y-%m-%d %H:%M:%S")
    Fin = datetime.strptime(request.session.get('fin'), "%Y-%m-%d %H:%M:%S")


    # Liste des véhicules déja réservé pandant la période
    liste_res    = Reservation.objects.filter(
                  ~(Q(debut__gt=debut) & Q(debut__gt=Fin)|
                  Q(Fin__lt=debut) & Q(Fin__lt=Fin))).values("vehicule") 

    #Liste des véhicules de la catégorie non réservé
    liste_vehicules =  Vehicule.objects.filter(
                 Q(categorie = categorie),
                 Q(DispoLocation = True),
                 ~Q(Immatriculation__in=liste_res))

    context = {
        'Titre': titre ,
        'date_resa': request.session.get('date_resa'),
        'nbjours': request.session.get('nbjours'),
        'categorie' : txt_categorie,
        'liste_vehicules': liste_vehicules
    }
    request.session['categorie'] =  categorie 
    request.session['txt_categorie'] = txt_categorie
    return render(request,'reservation/choixVehicule.html', context)


@login_required(login_url='/accounts/login/')
def choixClient(request,immatriculation):
    titre = 'Choix du client'
    vehicule = get_object_or_404(Vehicule, pk=immatriculation)
    liste_client = Partenaire.objects.filter(Nom= '*')

    if request.method == 'POST':
        RechPart_Form = FormRechPartenaire(request.POST,prefix = "RechPart")
        if RechPart_Form.is_valid():
            liste_client = Partenaire.objects.filter(Nom__icontains = RechPart_Form.cleaned_data['nom'])               
    else:
       RechPart_Form = FormRechPartenaire(prefix = "RechPart")


    context = {
        'Titre': titre ,
        'date_resa': request.session.get('date_resa'),
        'nbjours': request.session.get('nbjours'),
        'categorie' : request.session.get('txt_categorie'),
        'vehicule': vehicule,
        'liste_partenaire' : liste_client,
        'FormRechPart' : RechPart_Form,
    }
    request.session['immatriculation'] = immatriculation
    return render(request,'reservation/choixClient.html', context)


@login_required(login_url='/accounts/login/')
def add_driver(request,driver):
    titre = 'Choix du client'
    vehicule = get_object_or_404(Vehicule, pk = request.session.get('immatriculation'))
    liste_client = Partenaire.objects.filter(Nom= '*')
    client = Partenaire.objects.filter(pk= request.session.get('client_fact'))
    conducteur= Partenaire.objects.filter(pk= driver)

    if request.method == 'POST':
       RechPart_Form = FormRechPartenaire(request.POST  ,prefix = "RechPart")
       if RechPart_Form.is_valid():
          liste_client = Partenaire.objects.filter(Nom__icontains=  RechPart_Form.cleaned_data['nom']) 
    else:
       RechPart_Form = FormRechPartenaire(prefix = "RechPart")

    context = {
        'Titre': titre ,
        'date_resa': request.session.get('date_resa'),
        'nbjours': request.session.get('nbjours'),
        'categorie' : request.session.get('txt_categorie'),
        'vehicule': vehicule,
        'liste_partenaire' : liste_client,
        'FormRechPart' : RechPart_Form,
        'conducteur' : conducteur,
        'client' : client,
    }
    request.session['conducteur'] = driver
    return render(request,'reservation/choixClient.html', context)


@login_required(login_url='/accounts/login/')
def add_custumer(request,custumer):
    titre = 'Choix du client'
    vehicule = get_object_or_404(Vehicule, pk=request.session.get('immatriculation'))
    liste_client = Partenaire.objects.filter(Nom= '*')
    client = Partenaire.objects.filter(pk= custumer)
    conducteur= Partenaire.objects.filter(pk= request.session.get('conducteur'))

    if request.method == 'POST':
       RechPart_Form = FormRechPartenaire(request.POST  ,prefix = "RechPart")
       if RechPart_Form.is_valid():
          liste_client = Partenaire.objects.filter(Nom__icontains=  RechPart_Form.cleaned_data['nom']) 
      
    else:
       RechPart_Form = FormRechPartenaire(prefix = "RechPart")

    context = {
        'Titre': titre ,
        'date_resa': request.session.get('date_resa'),
        'nbjours': request.session.get('nbjours'),
        'categorie' : request.session.get('txt_categorie'),
        'vehicule': vehicule,
        'liste_partenaire' : liste_client,
        'FormRechPart' : RechPart_Form,
        'conducteur' : conducteur,
        'client' : client,
    }
    request.session['client_fact'] = custumer
    return render(request,'reservation/choixClient.html', context)


@login_required(login_url='/accounts/login/')
def saveResa(request):
    titre = 'Finaliser'
    vehicule = Vehicule.objects.get( pk= request.session.get('immatriculation'))

MSA/reservation/templates/reservation/categorie.html
{% extends 'home/base.html' %}
{% load resa_extras %}

{% block content %}

    <div> 
       <ul>
         <li>   
           Reservation pour {{ nbjours }} jour(s) 
           pour la periode du {{  date_resa.date_debut }} ({{  date_resa.heure_debut }}) 
           au {{  date_resa.date_fin }} ({{  date_resa.heure_fin }}) 
         </li>
       </ul>
    </div>


    <div> <h2>{{ Titre }} </h2></div>


    {% for categorie in liste_categories %}
    
         <article class="cat_vehicule">
             <a href="{% url 'reservation:choixVehicule' categorie=categorie.pk %}">
                <header> <h1>Categorie {{ categorie.categorie }}</h1> </header>
                <section>
                  <P>Tarif : {{ categorie.tarif }} euro/jr - Total : {{ prix_loc|hash:categorie.categorie }} </P>
                  <P>{{ categorie.description }}</P>
                </section>
            </a>
         </article>
    {% endfor %}
{% endblock %}

MSA/reservation/templates/reservation/choixClient.html
{% extends 'home/base.html' %}

{% block content %}
 
    <div> 
       <ul>
         <li>   
           Reservation pour {{ nbjours }} jour(s) 
           pour la periode du {{ date_resa.date_debut }} ({{ date_resa.heure_debut }}) 
           au {{ date_resa.date_fin }} ({{ date_resa.heure_fin }}) 
         </li>

        <li> {{ categorie }} </li>

        <li> Vehicule: {{ vehicule.Immatriculation }}  - {{ vehicule.Marque }} {{ vehicule.Description }} {{ vehicule.Couleur }} </li>
    
        {% for client in client %}
            <li> Client : {{ client }} </li> 
        {% endfor %}

        {% for conducteur in conducteur %} 
            <li> Conducteurs : {{ conducteur }} </li>
            <li><a href="{% url 'reservation:save' %}">Enregistrer la reservation</a></li>
        {% endfor %}
       </ul>
    </div>

    <div> <h2>{{ Titre }} </h2></div>

    {% if FormRechPart %}
        <form name="FormRechPart" action="#" method="post">
            {% csrf_token %}
            {{ FormRechPart }}
            <input type="submit" value="Rechercher">
        </form>
    {% endif %}

   {% if liste_partenaire %}
       <table>
            <thead>
                <tr>
                    <th>Numero</th>
                    <th>Titre</th>
                    <th>RaisonSociale</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Addresse</th>
                    <th>Telephone</th>
                    <th>Email</th>
                    <th>DateNaissance</th>
                    <th>NumeroPermis</th>
                    <th>DateCreation</th>
                </tr>
            </thead>
            <tbody>
                {% for partenaire in liste_partenaire %}
                <tr>
                    <td>
                        <a href="{% url 'partenaire:EditPartenaire' partenaire.pk %}"> Modifier </a> - 
                        <a href="{% url 'reservation:add_driver' partenaire.pk %}"> Conducteur</a> -
                        <a href="{% url 'reservation:add_custumer' partenaire.pk %}"> Client</a> 
                    </td>
                    <td>{{ partenaire.Titre }}</td>
                    <td>{{ partenaire.RaisonSociale }}</td>
                    <td>{{ partenaire.Nom }}</td>
                    <td>{{ partenaire.Prenom }}</td>
                    <td>{{ partenaire.Addresse }}</td>
                    <td>{{ partenaire.Telephone }}</td>
                    <td>{{ partenaire.Email }}</td>
                    <td>{{ partenaire.DateNaissance }}</td>
                    <td>{{ partenaire.NumeroPermis }}</td>
                    <td>{{ partenaire.DateCreation }}</td>
                </tr>
                {% endfor %}
             <tbody>
            <tfoot>
            </tfoot>
        </table> 
   {% else %}
       <p>Aucun partenaire trouve</p>
   {% endif %}



{% endblock %}

MSA/reservation/templates/reservation/choixVehicule.html
{% extends 'home/base.html' %}

{% block content %}

    <div> 
       <ul>
           <li>   
             Reservation pour {{ nbjours }} jour(s) 
             pour la periode du {{ date_resa.date_debut }} ({{ date_resa.heure_debut }}) 
             au {{ date_resa.date_fin }} ({{ date_resa.heure_fin }}) 
           </li>

           <li> {{ categorie }} </li>
      </ul>
    </div>

    <div> <h2>{{ Titre }}</h2></div>

    <div><a href="{% url 'vehicule:NewVehicule' %}">Nouveau vehicule</a></div>
   {% if liste_vehicules %}
       <table>
            <thead>
                <tr>
                    <th>Immatriculation</th>
                    <th>Marque</th>
                    <th>Description</th>
                    <th>Couleur</th>
                    <th>DatePMEC</th>
                    <th>NBPortes</th>
                    <th>NbCles</th>
                    <th>DispoVente</th>
                    <th>DispoLocation</th>
                </tr>
            </thead>
            <tbody>
                {% for vehicule in liste_vehicules %}
                <tr>
                    <td><a href="{% url 'reservation:choixClient' immatriculation=vehicule.pk %}"> {{ vehicule.Immatriculation }}</a></td>
                    <td>{{ vehicule.Marque }}</td>
                    <td>{{ vehicule.Description }}</td>
                    <td>{{ vehicule.Couleur }}</td>
                    <td>{{ vehicule.DatePMEC }}</td>
                    <td>{{ vehicule.NBPortes }}</td>
                    <td>{{ vehicule.NbCles }}</td>
                    <td>{{ vehicule.DispoVente }}</td>
                    <td>{{ vehicule.DispoLocation }}</td>
                </tr>
                {% endfor %}
             <tbody>
            <tfoot>
            </tfoot>
        </table> 
   {% else %}
       <p>Aucun vehicule trouve</p>
   {% endif %}
{% endblock %}

MSA/reservation/templates/reservation/editResa.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>{{ titre }}</h1>
    <h2><a href="{% url 'reservation:editContrat' resa.pk %}">Editer le contrat</a></h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                     {% if field.errors  %}
                       <p>{{ field.errors }}</p>
                     {% endif %}
                     <p>{{ field.label_tag }}</p> 
                     <p>{{ field }}</p>
               {% if field.help_text %}
                  <p class="help">{{ field.help_text|safe }}</p>
               {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}
<!-- {{ form.as_p }} -->

MSA/reservation/templates/reservation/index.html
{% extends 'home/base.html' %}

{% block content %}
    <h2>{{  Titre }}</h2>
    <div>
        <div><a href="{% url 'reservation:ListeReservation' %}">Liste de reservation</a></div>
    </div>
    <div class="fieldWrapper">
        <form method="POST" >{% csrf_token %}
           {{ form.non_field_errors }}
            <div class="fieldWrapper">
               <p> {{ form.date_debut.errors }}{{ form.heure_debut.errors }}</p>
               <p> <label for="{{ form.date_debut.id_for_label }}">Date de debut:</label></p>
               <p> {{ form.date_debut }}</p>   
               <p>{{  form.heure_debut }} </p>
            </div>

            <div class="fieldWrapper">
                <p>{{ form.date_fin.errors }}{{ form.heure_fin.errors }}</p>
                <p> <label for="{{ form.date_fin.id_for_label }}">Date de fin:</label></p>
                <p>{{ form.date_fin }} </p>  
                <p>{{  form.heure_fin }} </p>
            </div>

            <button type="submit" class="save btn btn-default">Creer une nouvelle reservation</button>
        </form>
    </div>
{% endblock %}

MSA/reservation/templates/reservation/listeResa.html
<html xmlns:v="urn:schemas-microsoft-com:vml"


<head>
<style id="Mon style">
table{
border-collapse:collapse;
top: auto; 
width:100% ; /*800 X 2000px*/
table-layout:fixed;
}
td {
 white-space: nowrap;
 overflow:visible; 
 font-size: 0.5em;    /*8 X 2000px*/
 border-width:0.3px; 
 border-style:solid;
 text-align:center;
 }
td a{
   display:block; 
   width:100%; 
   height:100%;
}
th {
 overflow: hidden;
 word-wrap:hyphenate;
 font-size:0.4em;   /*8 X 2000px*/
 border-width:0.5px; 
 border-style:solid;
 text-align:center;
 }
</style>
</head>

<body >
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">

    <h2>{{  Titre }}</h2>
    <div>
       {% if listResa %}
	   <table>
            <thead>	 
                <tr style="top: auto;">
                    <th style="width: 5%; "></th> <!-- 40px X 2000-->
                    {% for mois in nbDaysInMonth %}
                       <th colspan="{{ mois.nbjrs }}" style="font-size:0.8em;"> {{mois.mois}} </th>
                    {% endfor%}
                </tr>
                <tr>
                    <th style="width: 5%; font-size:0.9em;">
                        Vehicule
                    </th>
                    {% for date in allDates %}
                      <th> {{ date }}</th>
                    {% endfor%}
                </tr>
			</thead>
			<tbody>
			  {% for vehicule in listResa %}
                <tr>
				    {% for coll in vehicule %}
                         
						<td  
                           {% if coll.span != '0' %}
                             colspan="{{ coll.span }}"  {% endif %}   
 
                           style="background-color:{{ coll.color }}; {% if coll.first == 'X' %} font-size:0.9em; {% endif %} 
                         ">

						   {% if coll.link == 'X' %} 
                             <a href="{% url 'reservation:editResa' coll.resa.pk %}" > {% endif %} 

                            {% if coll.first == 'X'  %}  {{ coll.resa }} {% else %}  &nbsp; {% endif %} 

                           {% if coll.link == 'X'  %}  </a> {% endif %} 
						</td>

				    {% endfor %}	
				</tr>
			  {% endfor %}			
			</tbody>
	   </table>
	   {% endif %}
    </div>


</body>
</html>