MSA/MSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('vehicule/', include('vehicule.urls')),
    path('reservation/', include('reservation.urls')),
    path('partenaire/', include('partenaire.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

MSA/vehicule/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

app_name = 'vehicule'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:pk>/', views.detail, name='detail'),
    path('Add/', views.NewVehicule, name='NewVehicule'),
    path('Edit/<str:pk>/', views.EditVehicule, name='EditVehicule'),
    path('categories/', views.listeCategories, name='listeCategories'),
    path('editCategorie/<str:pk>/', views.editCategorie, name='editCategorie'),
    path('newCategorie/', views.newCategorie, name='newCategorie'),
    
]

MSA/vehicule/models.py
from django.db import models
from django.template.defaultfilters import truncatewords

# Create your models here.
class Marque(models.Model):
    Marque = models.CharField(max_length=20 , primary_key=True)
    Favoris = models.IntegerField(null = True)
    LogoUrl = models.FileField(upload_to='logo/',null = True)
    def __str__(self):
        return "%s" % (self.Marque)

class Categorie(models.Model):
    categorie = models.CharField(max_length=1, primary_key=True)
    tarif = models.DecimalField(max_digits=15, decimal_places=3)
    description = models.TextField()
    def __str__(self):
        return "%s" % (self.categorie )#+ " " + str(self.Tarif) + "€/jrs " + truncatewords(self.Description, 10))

class Vehicule(models.Model):
    Immatriculation = models.CharField(max_length=20, primary_key=True)
    Marque =  models.ForeignKey('Marque', on_delete=models.CASCADE,)
    Description = models.TextField()
    DatePMEC = models.DateField()
    Couleur = models.CharField(max_length=20, null=True,blank=True)
    NBPortes = models.IntegerField( null = True ) 
    NbCles = models.IntegerField(null = True)
    DispoVente = models.BooleanField(default=False)
    DispoLocation = models.BooleanField(default=False)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE, null=True, blank=True,)
    Archive = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    create_by = models.CharField(max_length=20, null=True, blank=True)
    def __str__(self):
        return "%s" % (self.Immatriculation)

MSA/vehicule/forms.py
from django import forms

from .models import Vehicule, Categorie
from .models import Marque

class PostForm(forms.ModelForm):
     class Meta:
        model = Vehicule
        fields = [   # '__all__'
            'categorie',
            'Immatriculation',
            'Marque',
            'Description',
            'DatePMEC',
            'Couleur',
            'NBPortes',
            'NbCles',
            'DispoVente',
            'DispoLocation',
            'Archive', ]
        #widgets = {
        #    'Description': Textarea(attrs={'cols': 80, 'rows': 3}),
        #}

class formCategorie(forms.ModelForm):
     class Meta:
        model = Categorie
        fields =  '__all__' 

MSA/vehicule/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from .models import Vehicule, Categorie
from .forms import PostForm, formCategorie

# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    liste_vehicules = Vehicule.objects.order_by('Immatriculation')
    context = {
        'liste_vehicules': liste_vehicules
    }
    return render(request,'vehicule/index.html', context)

@login_required(login_url='/accounts/login/')
def detail(request, pk):
    vehicule = get_object_or_404(Vehicule, pk=pk)
    return render(request, 'vehicule/detail.html', {'vehicule': vehicule})

@login_required(login_url='/accounts/login/')
def NewVehicule(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            vehicule = form.save(commit=False)
            #vehicule.create_by = request.user
            vehicule.save()
            return redirect('vehicule:detail', pk=vehicule.pk)
    else:
        form = PostForm()
    return render(request, 'vehicule/vehicule_edit.html', {'titre' : 'Nouveau véhicule','form': form})


@login_required(login_url='/accounts/login/')
def EditVehicule(request, pk):
    vehicule = get_object_or_404(Vehicule, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=vehicule)
        if form.is_valid():
            vehicule = form.save(commit=False)
            #vehicule.create_by = request.user
            vehicule.save()
            return redirect('vehicule:detail', pk=vehicule.pk)
    else:
        form = PostForm(instance=vehicule)
    return render(request, 'vehicule/vehicule_edit.html', {'titre' : 'Modification véhicule','form': form})

@login_required(login_url='/accounts/login/')
def listeCategories(request):
    liste_categories = Categorie.objects.order_by('categorie')
    context = {
        'liste_categories': liste_categories
    }
    return render(request,'vehicule/categories.html', context)

@login_required(login_url='/accounts/login/')
def editCategorie(request, pk):
    categorie = get_object_or_404(Categorie, pk=pk)
    if request.method == "POST":
        form = formCategorie(request.POST, instance=categorie)
        if form.is_valid():
            categorie = form.save(commit=False)
            categorie.save()
            return redirect('vehicule:listeCategories')
    else:
        form = formCategorie(instance=categorie)
    return render(request, 'vehicule/categorie_edit.html', {'titre' : 'Modification categorie','form': form})

@login_required(login_url='/accounts/login/')
def newCategorie(request):
    if request.method == "POST":
        form = formCategorie(request.POST)
        if form.is_valid():
            categorie = form.save(commit=False)
            categorie.save()
            return redirect('vehicule:listeCategories')
    else:
        form = formCategorie()
    return render(request, 'vehicule/categorie_edit.html', {'titre' : 'Nouvelle catégorie','form': form})

MSA/vehicule/templates/vehicule/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>M.S.A Application</title>
    <!--
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    -->
    <link rel="stylesheet" href="{% static 'css/vehicule.css' %}">
</head>
    <body>

        <div class="page-header">
            <h1><a href="/">MSA</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class=".col-md-3">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>

MSA/vehicule/templates/vehicule/categorie_edit.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>{{ titre }}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}
<!-- {{ form.as_p }} -->

MSA/vehicule/templates/vehicule/categories.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
    <div><a href="{% url 'vehicule:newCategorie' %}">Nouvelle categorie</a></div>
   {% if liste_categories %}
    {% for categorie in liste_categories %}
     <article class="vehicule" > 
        <header><h3><a style ="display:block;" href="{% url 'vehicule:editCategorie' categorie.pk %}">{{ categorie.categorie }}</a></h3></header>
        <section>
            <p>Tarif : {{ categorie.tarif }} Eur/jour</p>
            <p>Description : {{ categorie.description }} </p>         
        </section>
    </article>
    {% endfor %}
   {% else %}
       <p>Aucune categorie trouve</p>
   {% endif %}

{% endblock %}

MSA/vehicule/templates/vehicule/detail.html
{% extends 'home/base.html' %}

{% block content %}
   {% if vehicule %}
    <div><a href="{% url 'vehicule:EditVehicule' pk=vehicule.pk  %}">Modifier vehicule</a></div>
    <article class="post">
        <header> <h1>{{ vehicule.Immatriculation }} cat :{{ vehicule.categorie }}  </h1> </header>
        <section>
            <h2>{{ vehicule.Marque }} {{ vehicule.Description }} {{ vehicule.Couleur }}</h2>
            <p>Date MEC : {{ vehicule.DatePMEC }}</p>
            <p>Nb porte : {{ vehicule.NBPortes }}</p>
            <p>Nb cles :  {{ vehicule.NbCles }}</p>
            <p>{% if vehicule.DispoVente == True %}
                   Disponible a la vente
               {% else %}
                   Nom disponible a la vente
               {% endif %}
             </p>      
            <p>{% if vehicule.DispoLocation == True %}
                   Disponible a la location
               {% else %}
                   Nom disponible a la location
               {% endif %}
             </p>            
        </section>
    </article>
   {% else %}
       <p>Aucun vehicule trouve</p>
   {% endif %}
{% endblock %}

MSA/vehicule/templates/vehicule/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
    <div><a href="{% url 'vehicule:NewVehicule' %}">Nouveau vehicule</a></div>
   {% if liste_vehicules %}
    {% for vehicule in liste_vehicules %}
     <article class="vehicule" > <!--style="background-image: url( {% static 'logo/Renault.png' %} );"-->
        <img class ="logo-marque" src= "{% static vehicule.Marque.LogoUrl.name  %} " > <!--'logo/Renault.png'-->
        <header><h3><a style ="display:block;" href="{% url 'vehicule:detail' vehicule.pk %}">{{ vehicule.Immatriculation }} ({{ vehicule.categorie }})</a></h3></header>
        <section>
            <p>{{ vehicule.Marque }} {{ vehicule.Description }} {{ vehicule.Couleur }}</p>
            <p>Date MEC : {{ vehicule.DatePMEC }} </p>
            <p>{% if vehicule.DispoVente == True %}
                   Vente -
               {% endif %}
               {% if vehicule.DispoLocation == True %}
                   Location
               {% endif %}
             </p>            
        </section>
    </article>
    {% endfor %}
   {% else %}
       <p>Aucun vehicule trouve</p>
   {% endif %}

   <!--
       <table>
            <thead>
                <tr>
                    <th>Immatriculation</th>
                    <th>Marque</th>
                    <th>Description</th>
                    <th>Couleur</th>
                    <th>DatePMEC</th>
                    <th>NBPortes</th>
                    <th>NbCles</th>
                    <th>DispoVente</th>
                    <th>DispoLocation</th>
                </tr>
            </thead>
            <tbody>
                {% for vehicule in liste_vehicules %}
                <tr>
                    <td><a href="{% url 'vehicule:detail' vehicule.pk %}"> {{ vehicule.Immatriculation }}</a></td>
                    <td>{{ vehicule.Marque }}</td>
                    <td>{{ vehicule.Description }}</td>
                    <td>{{ vehicule.Couleur }}</td>
                    <td>{{ vehicule.DatePMEC }}</td>
                    <td>{{ vehicule.NBPortes }}</td>
                    <td>{{ vehicule.NbCles }}</td>
                    <td>{{ vehicule.DispoVente }}</td>
                    <td>{{ vehicule.DispoLocation }}</td>
                </tr>
                {% endfor %}
             <tbody>
            <tfoot>
            </tfoot>
        </table> 
       -->

{% endblock %}

MSA/vehicule/templates/vehicule/vehicule_edit.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>{{ titre }}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}
<!-- {{ form.as_p }} -->