MSA/MSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('vehicule/', include('vehicule.urls')),
    path('reservation/', include('reservation.urls')),
    path('partenaire/', include('partenaire.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

MSA/partenaire/urls.py
from django.urls import path
from django.conf.urls import include


from . import views

app_name = 'partenaire'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('Edit/<str:pk>/', views.EditPartenaire, name='EditPartenaire'),
]

MSA/partenaire/models.py
from django.db import models

# Create your models here.
class Partenaire(models.Model):
    type_titre = (
        ('1', 'Madame'),
        ('2', 'Monsieur'),
        ('3', 'Société'),
    )
    Titre = models.CharField(max_length=1, choices=type_titre, default='2',blank=True)
    RaisonSociale = models.CharField(max_length=50, null=True,blank=True)
    Nom = models.CharField(max_length=50,)
    Prenom = models.CharField(max_length=150)
    Adresse = models.TextField( null=True,blank=True)
    Telephone = models.CharField(max_length=20, null=True, blank=True)
    Email = models.EmailField(max_length=200, null=True, blank=True)
    DateNaissance = models.DateField( null=True , blank=True)
    NumeroPermis = models.CharField(max_length=50, null=True, blank=True)
    DatePermis = models.DateField( null=True , blank=True)
    VillePermis = models.CharField(max_length=30, null=True, blank=True)
    DateCreation = models.DateTimeField('Date de création', null=True, blank=True)
    def __str__(self):
        retour = self.Nom + " - " + self.Prenom
        if self.RaisonSociale is not None :
            retour = self.RaisonSociale + " ( " + retour + " ) " 
        return "%s" % (retour) 
    def save(self):
       self.Nom = self.Nom.upper()
       if self.RaisonSociale is not None : 
           self.RaisonSociale = self.RaisonSociale.upper()
       super(Partenaire, self).save()

MSA/partenaire/forms.py
from django import forms

from .models import Partenaire

class PartenaireForm(forms.ModelForm):
     class Meta:
        model = Partenaire
        fields =  '__all__'

class PartFilterForm(forms.Form):
        nom = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Nom'}),)
        prenom = forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'Prénom'}),)
        tel = forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'Tel'}),)

MSA/partenaire/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import Partenaire
from .forms import PartenaireForm, PartFilterForm

# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    liste_partenaire = Partenaire.objects.order_by('Nom')
    if request.method == "POST":
        form = PartFilterForm(request.POST)
        if form.is_valid():
            liste_partenaire = liste_partenaire.filter(Nom__icontains = form.cleaned_data['nom'])
            liste_partenaire = liste_partenaire.filter(Prenom__icontains = form.cleaned_data['prenom'])
            liste_partenaire = liste_partenaire.filter(Telephone__icontains = form.cleaned_data['tel'])
              
    else :
      form = PartFilterForm()



    titre = 'Liste des Partenaires'
    context = {
        'Titre': titre ,
        'Tableau' : '',
        'liste_partenaire': liste_partenaire,
        'form' : form
    }
    return render(request,'partenaire/index.html', context)

@login_required(login_url='/accounts/login/')
def new(request):
    if request.method == "POST":
        form = PartenaireForm(request.POST)
        if form.is_valid():
            partenaire = form.save(commit=False)
            #vehicule.create_by = request.user
            partenaire.save()
            return redirect('partenaire:index')
    else:
        form = PartenaireForm()
    return render(request, 'partenaire/partenaire_edit.html', {'titre' : 'Nouveau partenaire','form': form})

@login_required(login_url='/accounts/login/')
def EditPartenaire(request, pk):
    partenaire = get_object_or_404(Partenaire, pk=pk)
    if request.method == "POST":
        form = PartenaireForm(request.POST, instance=partenaire)
        if form.is_valid():
            partenaire = form.save(commit=False)
            partenaire.save()
            return redirect('partenaire:index')
    else:
        form = PartenaireForm(instance=partenaire)
    return render(request, 'partenaire/partenaire_edit.html', {'titre' : 'Modification partenaire','form': form})

MSA/partenaire/templates/partenaire/index.html
{% extends 'home/base.html' %}
{% load static %}
{% load extras %}


{% block content %}
    <div  class="content-item-menu">
        <a href="{% url 'partenaire:new' %}">Nouveau partenaire</a>
    </div>
    <div  class="content-item-filtre"> 
        <form action="#" method="post">{% csrf_token %}
            Filtre : {{ form.nom }} {{ form.prenom }} {{ form.tel }}
          <!--<input type="text" name="nom" value="Nom">
           <input type="text" name="prenom" value="Prenom">
           <input type="text" name="tel" value="tel">--> 
           <input type="submit" value="Filtrer">
        </form>
    </div>
   {% if liste_partenaire %}
      {% if Tableau == 'X'  %}
       <table>
            <thead>
                <tr>
                    <th>Numero</th>
                    <th>Titre</th>
                    <th>RaisonSociale</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Addresse</th>
                    <th>Telephone</th>
                    <th>Email</th>
                    <th>DateNaissance</th>
                    <th>NumeroPermis</th>
                    <th>DateCreation</th>
                </tr>
            </thead>
            <tbody>
                {% for partenaire in liste_partenaire %}
                <tr>
                    <td><a href="{% url 'partenaire:EditPartenaire' partenaire.pk %}"> {{ partenaire.pk }}</a></td>
                    <td>{{ partenaire.Titre }}</td>
                    <td>{{ partenaire.RaisonSociale }}</td>
                    <td>{{ partenaire.Nom }}</td>
                    <td>{{ partenaire.Prenom }}</td>
                    <td>{{ partenaire.Adresse }}</td>
                    <td>{{ partenaire.Telephone }}</td>
                    <td>{{ partenaire.Email }}</td>
                    <td>{{ partenaire.DateNaissance }}</td>
                    <td>{{ partenaire.NumeroPermis }}</td>
                    <td>{{ partenaire.DateCreation }}</td>
                </tr>
                {% endfor %}
             <tbody>
            <tfoot>
            </tfoot>
        </table> 
      {% else %}
         {% for partenaire in liste_partenaire %}

         <article class="content-item" > 
            <img class ="logo-partenaire" src= "{% static partenaire.Titre|partlogo %} " >
             <div style="height:40px" >
                 <a href="{% url 'partenaire:EditPartenaire' partenaire.pk %}"> 
                        <h3> {{ partenaire.Nom }} {{ partenaire.Prenom}}  </h3>
                 </a>
            </div>
            <div style="height:200px; vertical-align: top;">
                {% if partenaire.RaisonSociale %} <div> {{ partenaire.RaisonSociale }} </div> {% endif %} 
                <div> {{ partenaire.Adresse|linebreaks }}</div>
                <div>tel : {{ partenaire.Telephone }} </div>
                <div> Ne le {{ partenaire.DateNaissance }}</div>
            </div>
          </article>
         {% endfor %}
      {% endif %}
   {% else %}
       <p>Aucun partenaire trouve</p>
   {% endif %}
{% endblock %}

MSA/partenaire/templates/partenaire/partenaire_edit.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>{{ titre }}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
         <div>
           <button type="submit" class="save btn btn-default">Enregistrer</button>
         </div>
        {% for field in form %}
            <div style=" width:340px; height:auto; display:inline-block; vertical-align:top; ">
                     {% if field.errors  %}
                       <p>{{ field.errors }}</p>
                     {% endif %}
                     <p>{{ field.label_tag }}</p> 
                     <p>{{ field }}</p>
               {% if field.help_text %}
                  <p class="help">{{ field.help_text|safe }}</p>
               {% endif %}
            </div>
        {% endfor %}

    </form>
{% endblock %}
<!-- {{ form.as_p }} -->