MSA/MSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('vehicule/', include('vehicule.urls')),
    path('reservation/', include('reservation.urls')),
    path('partenaire/', include('partenaire.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

MSA/home/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
]

MSA/partenaire/urls.py
from django.urls import path
from django.conf.urls import include


from . import views

app_name = 'partenaire'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('Edit/<str:pk>/', views.EditPartenaire, name='EditPartenaire'),
]

MSA/reservation/urls.py
from django.urls import path
from django.conf.urls import include


from . import views

app_name = 'reservation'
urlpatterns = [
    path('', views.index, name='index'),
    path('categorie/', views.choixCategorie, name='choixCategorie'),
    path('choixClient/<str:immatriculation>', views.choixClient, name='choixClient'),
    path('choixVehicule/<str:categorie>', views.choixVehicule, name='choixVehicule'),
    path('liste/', views.ListeReservation, name='ListeReservation'),
    path('add_custumer/<str:custumer>', views.add_custumer, name='add_custumer'),
    path('add_driver/<str:driver>', views.add_driver, name='add_driver'),
    path('save/', views.saveResa, name='save'),
    path('editResa/<str:pk>', views.editResa, name='editResa'),
    path('editContrat/<str:pk>', views.editContrat, name='editContrat'),
]

MSA/vehicule/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

app_name = 'vehicule'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:pk>/', views.detail, name='detail'),
    path('Add/', views.NewVehicule, name='NewVehicule'),
    path('Edit/<str:pk>/', views.EditVehicule, name='EditVehicule'),
    path('categories/', views.listeCategories, name='listeCategories'),
    path('editCategorie/<str:pk>/', views.editCategorie, name='editCategorie'),
    path('newCategorie/', views.newCategorie, name='newCategorie'),
    
]

MSA/home/models.py
from django.db import models

# Create your models here.

MSA/home/views.py
from django.shortcuts import render
from django.shortcuts import redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    context = {
        'Tire': 'Accueil'
    }
    return render(request,'home/index.html', context)

MSA/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>M.S.A Application</title>
        <meta charset="utf-8" />   
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />

        <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
        <script type="text/javascript" src="{% static '/admin/js/core.js' %}"></script>

        <link rel="stylesheet" type="text/css" media="all" href="{% static '/css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/admin/css/widgets.css' %}">
        <style>.calendar>table>caption{caption-side:unset}</style><!--caption fix for bootstrap4-->
        {{ form.media }}        {# Form required JS and CSS #}

    </head>

   <!-- Structure de notre page: -->
   <!-- https://viseo.developpez.com/tutoriels/css/responsive-design/ -->
   <body>
      <div class="layout-main">
         <div class="main">
            <div class="layout-menu">

                <!-- Login-->
                <div class="login" style="display:block; background-color:#125b80;">
                    {% if user.is_authenticated %}
                        <p style="margin:0px">Bonjour {{ user.username }} ! </p>
                        <p style="margin:0px"><a href="{% url 'home:logout' %}">Se deconnecter</a></p>
                    {% else %}
                        <a href="{% url 'home:login' %}">Connection</a>
                    {% endif %}
                </div>

               <!-- Menu -->
               <div class="menu">
                    <nav>
                        <ul>
                            <li><a href="{% url 'home:index' %}">Home</a></li>
                            <li><a href="{% url 'vehicule:listeCategories' %}">Categorie</a></li>
                            <li><a href="{% url 'vehicule:index' %}">Vehicules</a></li>
                            <li><a href="{% url 'partenaire:index' %}">Partenaires</a></li>
                            <li><a href="{% url 'reservation:index' %}">Reservation</a></li>
                        </ul>
                    </nav>
                  
                    <select onChange="window.location.href=this.value">
                        <option selected="selected">Choisir un menu</option>
                        <option value="{% url 'home:index' %}">Home</option>
                        <option value="{% url 'vehicule:listeCategories' %}">Categorie</option>
                        <option value="{% url 'vehicule:index' %}">Vehicules</option>
                        <option value="{% url 'partenaire:index' %}">Partenaires</option>
                        <option value="{% url 'reservation:index' %}">Reservation</option>
                    </select>
               </div>
               
            </div><div class="layout-content">
               <!-- Contenu -->
               <div class="content">

                     {% block content %}
                      <!-- <div class="content-item"> -->
                      <!-- <div class="article"> -->
                     {% endblock %}

               </div>
            </div><div class="layout-adv">
               <!-- Publicités -->
               <div class="adv">
                     {% block adv %}
                     <!--  <div class="adv-item"> -->
                     {% endblock %}
               </div>
            </div>
         </div>
      </div>
   </body>
</html>

MSA/home/templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}
<table style="width:100%">
  <tbody>
    <tr>
        <td> 
            {% if user.is_authenticated %}
               <h2> Bonjour {{ user.username }} ! </h2>
            {% endif %}
        </td> 
        <td style="text-align:right">
            {% now "j F Y H:i" %}
        </td>
    </tr>
  </tbody>
</table>

{% endblock %}